import React, { useState } from 'react';
import { Sparkles, Music, Loader2, Play } from 'lucide-react';

// --- Component Helpers (ต้องนำเข้าจาก ScriptGenerator.jsx) ---
// Note: AccentButton และ FormInput ถูกย้ายไปอยู่ใน ScriptGenerator.jsx แล้ว
// เราจะสมมติว่ามันถูกส่งเป็น Props หรือเป็น Global Component

const AccentButton = ({ children, onClick, disabled, className = '', icon: Icon, type = 'button' }) => (
    <button
        type={type}
        onClick={onClick}
        disabled={disabled}
        className={`flex items-center justify-center gap-2 px-4 py-2 text-sm font-bold rounded-xl transition-all shadow-md active:scale-[0.98] whitespace-nowrap ${
            disabled
                ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                : 'bg-orange-600 text-white hover:bg-orange-700 shadow-orange-300/50'
        } ${className}`}
    >
        {Icon && <Icon size={16} />}
        {children}
    </button>
);

const FormInput = ({ label, value, onChange, placeholder, type = 'text', step, min, max, icon: Icon, className = '' }) => (
    <div className={`flex flex-col space-y-2 ${className}`}>
        <label className="text-sm font-semibold text-gray-700 flex items-center gap-2">
            {Icon && <Icon size={16} className="text-orange-500" />}
            {label}
        </label>
        <input
            type={type}
            value={value}
            onChange={onChange}
            placeholder={placeholder}
            step={step}
            min={min}
            max={max}
            className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-orange-500 transition-all text-gray-900 placeholder-gray-400 bg-white"
        />
    </div>
);

// -------------------------------------------------------------

const MusicGenerator = ({ userCredit, consumeCredit, user }) => {
    const [topic, setTopic] = useState('');
    const [genre, setGenre] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [musicResult, setMusicResult] = useState(null);
    const MUSIC_COST = 0; // 🎯 ต้นทุน 0 เครดิต (Unlimited) ตามแผนธุรกิจ
    
    // ตัวอย่าง Genres ที่เป็นที่นิยม
    const popularGenres = [
        "Pop", "Rock", "Hip-Hop", "EDM", "Jazz", "Acoustic", 
        "Ambient (สำหรับ Meditation/ธรรมะ)", "Cinematic (สำหรับ Trailer)", "Lofi"
    ];

    const handleGenerateMusic = async () => {
        if (!topic.trim() || !genre.trim()) {
            alert("กรุณาป้อนทั้งหัวข้อและแนวเพลงครับ");
            return;
        }

        // --- 1. Check Credit (ถึงแม้จะเป็น 0 แต่ก็ต้องใช้ Logic นี้เผื่ออนาคต) ---
        if (userCredit < MUSIC_COST) {
            alert(`⚠️ เครดิตไม่พอ! คุณมี ${userCredit} เครดิต แต่ต้องใช้ ${MUSIC_COST} เครดิต`); 
            return;
        }

        // --- 2. Start Generation (ไม่มีการหักเครดิตเพราะ MUSIC_COST = 0) ---
        setIsLoading(true);
        setMusicResult(null);

        try {
            // 💡 โค้ดจริงจะมีการเรียก Suno API, Udio API, หรือ Google Music API ที่นี่
            // สำหรับตอนนี้เราจำลองการทำงาน
            await new Promise(resolve => setTimeout(resolve, 3000)); 

            // จำลองผลลัพธ์
            setMusicResult({
                title: `${genre} Beat: ${topic}`,
                duration: "1:30",
                url: "https://placehold.co/400x100/34D399/FFFFFF?text=Generated+Music+File",
                lyrics: "Sample lyrics generated by AI: Rhythm is calling, the future is bright, viral content all day and night."
            });
            
        } catch (error) {
            console.error("Music Generation Error:", error);
            alert("เกิดข้อผิดพลาดในการสร้างเพลง: " + error.message);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="bg-white p-5 md:p-8 rounded-xl shadow-lg border border-gray-200">
            <h2 className="text-2xl font-extrabold text-gray-900 flex items-center gap-2 mb-6">
                <Music size={24} className="text-blue-600"/> 
                โมดูล 2: สร้างเพลง/บีทติดไวรัล (Unlimited!)
            </h2>

            <div className="space-y-6 pt-3">
                <FormInput
                    label="อธิบายเพลงที่ต้องการ (ยิ่งละเอียด ยิ่งดี)"
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    placeholder="เช่น: เพลงบีทสนุกๆ สไตล์ Lofi สำหรับวิดีโอท่องเที่ยวญี่ปุ่น"
                    icon={Sparkles}
                />
                <FormInput
                    label="แนวเพลง (Genre)"
                    value={genre}
                    onChange={(e) => setGenre(e.target.value)}
                    placeholder={`เช่น: ${popularGenres.join(', ')}`}
                    icon={Music}
                    className="mb-6"
                />
            </div>
            
            <div className="flex justify-end mt-6">
                <AccentButton 
                    onClick={handleGenerateMusic} 
                    disabled={!topic.trim() || !genre.trim() || isLoading}
                    icon={isLoading ? Loader2 : Music}
                    className={isLoading ? "animate-pulse" : ""}
                >
                    {isLoading ? "กำลังสร้าง (30s)..." : "สร้างเพลง/บีทฟรีทันที"}
                </AccentButton>
            </div>

            {/* Music Result Display */}
            {musicResult && (
                <div className="mt-8 p-5 bg-blue-50 border border-blue-200 rounded-xl shadow-inner">
                    <h3 className="text-lg font-bold text-blue-800 mb-3 flex items-center gap-2">
                        <Play size={20}/> เพลงของคุณพร้อมแล้ว!
                    </h3>
                    <p className="text-sm text-gray-700 mb-4">
                        <span className="font-semibold">{musicResult.title}</span> ({musicResult.duration})
                    </p>
                    
                    {/* จำลองการเล่นเพลง */}
                    <div className="w-full h-16 bg-blue-300 rounded-lg flex items-center justify-between p-3 mb-4">
                        <p className="font-mono text-xs text-blue-900">Audio Player Placeholder</p>
                        <AccentButton className="!bg-blue-600 hover:!bg-blue-700 !px-3 !py-1.5 !text-sm">
                            ดาวน์โหลด MP3
                        </AccentButton>
                    </div>

                    <div className="border-t border-blue-200 pt-3">
                        <p className="text-xs font-semibold text-blue-700">เนื้อเพลง (Lyrics):</p>
                        <p className="text-xs text-gray-600 mt-1 italic whitespace-pre-wrap">{musicResult.lyrics}</p>
                    </div>
                </div>
            )}
        </div>
    );
};

export default MusicGenerator;